export {
  createOfficeEditor,
  getActiveOfficeEditorCount,
  loadOfficeEditorApi,
  type CreateOfficeEditorOptions,
  type OfficeEditorInput,
  type OfficeEditorInstance,
  type OfficeDownloadCallbackResult,
  type OfficeEditorMode,
  type OfficeEditorSourceKind,
  type OfficeEditorState,
  type OfficeHostUrlContext,
  type OfficeHostUrlResolver,
  type OfficeSaveBehavior,
  type OfficeSaveCallbackResult,
  type OfficeSaveToNewFormatConfirmationOptions,
} from './lib/office-editor';
